### ISSUE TITLE
Incorrect playerCount Value in Clan Data

### ISSUE THREAD

**Issue by Skoivumaki** [Alt-Org/Altzone-Server#100]
### Description
The playerCount value in the Clan data appears incorrect in some Clans.
Using GET Clan by id (https://altzone.fi/api/clan/65ccea8f9934745d0c77033b?with=Player) at time, returned playerCount is shown as 7, but there are actually 10 players total (including admin) under the Player array.
### Steps to Reproduce
Note: It seems clans without admins are unaffected and clans with admins start behaving weird when clan has more than 3 players could be wrong.
1. Retrieve the data for a clan with more than three players and at least one admin
2. Compare playerCount value with the actual amount of players in the Player array.
### Example Clan _ids Exhibiting the Issue
- 65ccea8f9934745d0c77033b
- 65ccee0d9934745d0c7706e8
### Additional
Created a new fresh clan and even with 4 players playerCount stayed normal, maybe affected data is old idk.

**Comment by MikhailDeriabin** [comment]
Thanks for your report.

The playerCount field can indeed contain some bugs for sure, because it was made more as a "hot fix" rather than a proper solution.

We will look into all such counters a bit later, since we need to implement some other tasks right now. 

I will check whenever it is possible to add some quick temporary solution and get you an update within this week.

**Comment by MikhailDeriabin** [comment]
Alright, I have started to improve the logic of the counters, which are used for such _playerCount_ fields and I think that I should be able to finish it on the next week.

After this logic will be done and will be added to the API, I can have a look at the database itself and write some script to fix the _playerCount_ field old values.

I again will inform you when all of this will be done.
