### ISSUE TITLE
Add flea market GET endpoints for reading items

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#196]
[Swagger](https://swagger.altzone.fi/#/FleaMarket)

- [x] Get all flea market items endpoint
- [x] Get flea market item by _id endpoint

**Comment by MikhailDeriabin** [comment]
@sebastyijan-fi 

Do you have some problems with the task, what is its status atm?

**Comment by PlayJeri** [comment]
@MikhailDeriabin 

Some questions about the new architecture and the flea market and voting related issues.

So apparently there is no existing code for the flea market and voting?

The new architecture has the clan_module and clanInventory modules that overlap each other a lot. Biggest difference seems to be the lack of clan module in the clanInventory.
And the clan_module has clan folder that is pretty much a copy of the clan module. 
Why is the structure like this?
Since clan_module and clanInvetory both contain nearly identical item.service.ts files if I make changes to that file should the other file be changed aswell?
If I need to use item or room service from which module should that be from?
Should the flea market and voting go into one of these modules or be a separate thing?


I'm a bit confused about the new architecture so I think I need some information about the changes made and how to use and build on this new structure before I start working on these issues. So if you write me some instructions here or in discord or if you prefer we can have a meeting. Next Tuesday would work for me.

**Comment by MikhailDeriabin** [comment]
@PlayJeri 

No, there are not, it was planned that the Niklas will do this milestone, but he left the project.

The _clan_module_ will be removed, I used it pretty much for creating the jest setup and trying out some ideas, just ignore it. Notice however, that you should create a copy of an item being sold to the `FleamarketItem` collection, and remove the copied item from clan items, and vice versa. It is done to decrease the amount of items to search from in the flea market, because we are not sure how much each clan can have items, it can be like 100 per clan, and in that case DB will struggle to search throw all of them.

In the schema the voting and flea market are separate modules. You can think about them as an addition to existing functionality, which should not affect existing code, but rather be build on top of it.

Yes, I think meeting would be better, what about next Tuesday at 11.00 am?

**Comment by PlayJeri** [comment]
@MikhailDeriabin
Tuesday at 11.00 works 👍
