### ISSUE TITLE
Add /fleaMarket/buy endpoint for proposing an item to buy

### ISSUE THREAD

**Issue by MikhailDeriabin** [Alt-Org/Altzone-Server#198]
[Swagger](https://swagger.altzone.fi/#/FleaMarket/post_fleaMarket_buy)
[Flow chart, item buying process](https://github.com/Alt-Org/Altzone-Server/tree/dev/doc/img/flea_market)

Notice that the notifications mechanism is currently under development, you do not have to implement it yourself. If it is not yet implemented just skip the notification sending part, but make all necessary DB operations. If you are unsure whether it is implemented or not you can ask me in this Issue comment section.

- [ ] write /fleaMarket/buy endpoint

**Comment by PlayJeri** [comment]
@MikhailDeriabin 

About the gameCoins when buying the item from fleamarket.
The diagram shows to check that clan has enough of game coins before you can book the item. But since the voting can take some time the amount of game coins can change before voting is done and item is bought. So should the item price be taken away from clan game coins while the voting is going on and then returned if the vote is not to buy the item. Or do we just check the game coins amount again if the vote is to buy the item and then the buying fails if there is not enough coins left.

I think we should go with the option to reduce the item price from clan coins while the voting is going on since that would make sure clans can't reserve every single item from the flea market just to annoy other players and to avoid the issue of not having enough coins left after the vote passes.

But I wanted to ask you if you had any discussions about this with the other teams.

**Comment by PlayJeri** [comment]
@MikhailDeriabin 

Couple of questions.
First about the voting schema.
I think that we could reduce the number of fields in the voting schema.
I don't think that we need startedAt endedAt and endsOn fields.
The endsOn field alone should be enough. And I think the expired votings could just be deleted from the db and so we don't need the endedAt field either. 
Next the player_ids field might not be necessary since the votes array already has the player_ids of voters.
And maybe the organizer_id could also have the clan id to make queries simpler.

Second.
How are we going to track the voting time.
I made a version that uses the setTimeout to trigger the votingCheck method after the 10 minutes but I don't think that is a good idea in production so we might consider using some library for this.
Any ideas?

**Comment by MikhailDeriabin** [comment]
@PlayJeri 

1. Voting schema
 - The `startedAt` and `endedAt` fields, I think they can be removed, yes. It was long time, when I was planing it so, I do not remember for what purpose they are. May be just for information to display on the client side like "The voting has started 12.1". 
 - The `player_ids` field can be removed also.
 - The `organizer_id` should be player's _id since the voting can be organized not only for clans, but also in some other cases. I think this field can be renamed to `organizer` and it can be nested object, which content is defined by the type of voting. So for the item selling and buying it can be:
```ts
{
  player_id: string;
  clan_id: string;
}
```

2. Voting expiration
 - The `setTimeout()` is not the best solution, yes.
 - The solution should not rely on RAM, since the API can be reloaded on server and all timers will be gone.
   I think that you can remove the voting right away when it has got all necessary votes, at least for now. 
   Expired votings can removed whenever somebody is making GET request and all expired votings are removed. The idea is about the same as it was with _/leaderboard_.
