### ISSUE TITLE
images´ size is too heavy , each about 1mb , may be there is a way to optimize them before sending ?

### ISSUE THREAD

**Issue by leolab1337** [Alt-Org/Altzone-Server#24]
e.g https://altzone.fi/api/public/site/comics/Aapo/image11.png

**Comment by MikhailDeriabin** [comment]
It is optimized by compressing images with gzip. If you have a look at the "Content-Encoding"-header, it does come compressed. 
The "Content-Length"-header is not available since calculating the size adds a bit overhead on the server side with no advantages.
The size in dev tools is size of an unpacked image
