### ISSUE TITLE
Feature request: getMe functional

### ISSUE THREAD

**Issue by leolabdev** [Alt-Org/Altzone-Server#289]
## What do you want to see in the API?

we want to have an endpoint (e.g. /auth/getMe) to get the same data that we get when logging in

![image](https://github.com/user-attachments/assets/d475ebcb-caca-48c1-8b4c-1e0d7308d180)

The problem is that there are many cases when the current user data becomes irrelevant, we need a convenient mechanism to handle this.
We can promise that we will not abuse the server unnecessarily. We will try to make requests optimized as much as possible

**Comment by MikhailDeriabin** [comment]
@leolabdev 

Now, when I think about it, it is possible that you have to make queries to this endpoint, because we have two places, where data of clans etc. can be changes in game and I guess on site. So you can not be sure about clan data, that it is up-to-date.

I think that in future, some notifications can be sent via MQTT, but for now Idk mb every 30 min make requests to this endpoint.

**Comment by leolabdev** [comment]
At the moment, it would be convenient for us, for example, if a user leaves the clan, we make such a request to make sure that he left and update his state. But yes, if you should take into account that the user can be kicked from the clan and then this will be a problem...

**Comment by MikhailDeriabin** [comment]
You are getting a response from server with success or error, you should not make additional request to a API if the player leaves a clan, this is exactly what I kind of requests I do not want to get from frontend and this is "abuse the server unnecessarily"

In case player was kicked from a clan, it is ok to make the request, because atm site does not get any notifications about it

**Comment by leolabdev** [comment]
okay let's make it every 30 min for start

**Comment by leolabdev** [comment]
@MikhailDeriabin How is the situation ?

**Comment by MikhailDeriabin** [comment]
@PlayJeri 

Can you have a look at this issue?

You can add the functionality to the _/profile/info_

**Comment by PlayJeri** [comment]
@MikhailDeriabin @leolabdev 

So do we need an endpoint to get the same data as the /auth/signIn for logged in user or a cron job sending that data via MQTT every 30 minutes or both?

**Comment by MikhailDeriabin** [comment]
@PlayJeri 

just a simple HTTP GET endpoint will be fine
